# Generated by Django 4.1.2 on 2023-03-25 15:53
# Modified by Ben on the same day.

from django.db import models, migrations


def load_units(apps, schema_editor):
    Unit = apps.get_model("grocerylist", "Unit")

    Unit(
        measurement_type = "count",
        name = "count",
    ).save()

    Unit(
        measurement_type = "weight",
        name = "gram",
    ).save()
    Unit(
        measurement_type = "weight",
        name = "kilogram",
    ).save()
    Unit(
        measurement_type = "weight",
        name = "ounce",
    ).save()
    Unit(
        measurement_type = "weight",
        name = "pound",
    ).save()

    Unit(
        measurement_type = "volume",
        name = "liter",
    ).save()
    Unit(
        measurement_type = "volume",
        name = "milliliter",
    ).save()
    Unit(
        measurement_type = "volume",
        name = "teaspoon",
    ).save()
    Unit(
        measurement_type = "volume",
        name = "tablespoon",
    ).save()
    Unit(
        measurement_type = "volume",
        name = "fluid ounce",
    ).save()
    Unit(
        measurement_type = "volume",
        name = "cup",
    ).save()
    Unit(
        measurement_type = "volume",
        name = "pint",
    ).save()
    Unit(
        measurement_type = "volume",
        name = "quart",
    ).save()
    Unit(
        measurement_type = "volume",
        name = "gallon",
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0002_recipe_unit_ingredient'),
    ]

    operations = [
        migrations.RunPython(load_units)
    ]
